/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import chat.ChatInterface;
import chat.Message;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author shenugayana
 */
public class Home extends javax.swing.JFrame implements MouseListener, KeyListener {

    String username;
    ChatInterface chat;
    List<Message> msgs = new ArrayList<>();
    List<String> users = new ArrayList<>();

    /**
     * Creates new form ChatView
     */
    public Home(ChatInterface chat, String username) throws RemoteException {
        initComponents();
        this.chat = chat;
        this.username = username;
        chat.login(username);
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lghLabel = new javax.swing.JLabel();
        hpyLabel = new javax.swing.JLabel();
        sadLabel = new javax.swing.JLabel();
        supLabel = new javax.swing.JLabel();
        angLabel = new javax.swing.JLabel();
        tngLabel = new javax.swing.JLabel();
        glsLabel = new javax.swing.JLabel();
        ywnLabel = new javax.swing.JLabel();
        chatInputText = new javax.swing.JTextField();
        sendButton = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatListTextArea = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        userListTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("arulWing");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lghLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        getContentPane().add(lghLabel);
        lghLabel.setBounds(270, 600, 122, 104);

        hpyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png"))); // NOI18N
        hpyLabel.setPreferredSize(new java.awt.Dimension(122, 104));
        getContentPane().add(hpyLabel);
        hpyLabel.setBounds(140, 600, 122, 104);

        sadLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        getContentPane().add(sadLabel);
        sadLabel.setBounds(400, 600, 122, 104);

        supLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        getContentPane().add(supLabel);
        supLabel.setBounds(530, 600, 122, 104);

        angLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        getContentPane().add(angLabel);
        angLabel.setBounds(660, 600, 122, 104);

        tngLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        getContentPane().add(tngLabel);
        tngLabel.setBounds(790, 600, 122, 104);

        glsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png"))); // NOI18N
        getContentPane().add(glsLabel);
        glsLabel.setBounds(920, 600, 122, 104);

        ywnLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.png"))); // NOI18N
        getContentPane().add(ywnLabel);
        ywnLabel.setBounds(1050, 600, 122, 104);

        chatInputText.setBorder(null);
        getContentPane().add(chatInputText);
        chatInputText.setBounds(170, 550, 980, 40);

        sendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BtnSend.png"))); // NOI18N
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        getContentPane().add(sendButton);
        sendButton.setBounds(1158, 550, 42, 40);

        nameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 23)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(78, 75, 79));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("ARULWING");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(130, 30, 130, 40);

        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(55, 178, 204));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(55, 178, 204)));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton);
        logoutButton.setBounds(1150, 10, 120, 60);

        jScrollPane3.setBorder(null);

        chatListTextArea.setEditable(false);
        chatListTextArea.setBorder(null);
        chatListTextArea.setContentType("text/html"); // NOI18N
        chatListTextArea.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <h1 color='red'>Viji</h1>\n    </p>\n  </body>\n</html>\n");
        jScrollPane3.setViewportView(chatListTextArea);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(50, 120, 980, 400);

        jScrollPane2.setBackground(new java.awt.Color(198, 225, 226));
        jScrollPane2.setBorder(null);

        userListTextArea.setEditable(false);
        userListTextArea.setBackground(new java.awt.Color(198, 225, 226));
        userListTextArea.setColumns(20);
        userListTextArea.setRows(5);
        jScrollPane2.setViewportView(userListTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1090, 190, 150, 260);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 178, 204));
        jLabel2.setText("online users");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1130, 160, 88, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BgHome.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        sendNewMessage();
    }//GEN-LAST:event_sendButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        try {
            chat.logout(username);  //use the reference "chat" to call remote methods
            System.exit(0);
            //catch the exceptions may occur, Rubbish URL, RemoteException
        } catch (RemoteException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angLabel;
    private javax.swing.JTextField chatInputText;
    private javax.swing.JTextPane chatListTextArea;
    private javax.swing.JLabel glsLabel;
    private javax.swing.JLabel hpyLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lghLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel sadLabel;
    private javax.swing.JLabel sendButton;
    private javax.swing.JLabel supLabel;
    private javax.swing.JLabel tngLabel;
    private javax.swing.JTextArea userListTextArea;
    private javax.swing.JLabel ywnLabel;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        userListTextArea.setLineWrap(true);
        setImages();
        addListeners();      
        this.nameLabel.setText(username);
        this.setVisible(true);
        setLocationRelativeTo(null);            // to visible the GUI in the middle of the screen
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    refresh();                  // this thread is used to refresh the chat window by every second 
                    try {                       // to display whole chat list
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        t1.start();
    }

    public void displayChatList() throws RemoteException {
        chatListTextArea.setText("");
        msgs = chat.getAllMessages();
        String doc = "<html><body><table>";
        for (Message m : msgs) {
            if (!((m.getUsername().equals(username)) && (m.getType().equals("join")))) {             
                String smileyName = m.getSmiley();               
                Date date = m.getDate();
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                String a = dateFormat.format(date);
                SimpleDateFormat parseFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                SimpleDateFormat printFormat = new SimpleDateFormat("HH:mm:ss");
                try {
                    Date time = parseFormat.parse(a);
                    if (smileyName == null) {
                        doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getUsername() 
                                + "</b></font></td><td> " 
                                + m.getMsg() 
                                + "</td></tr>";
                    } else {                  
                        doc += "<tr><td>" 
                                + printFormat.format(time) 
                                + "</td><td><font color='rgb(55,178,204)'><b>" 
                                + m.getUsername()  
                                + "</b></font></td><td><img src= '" 
                                + this.getClass().getResource("/images/"+smileyName) 
                                + "' width=122 height=104 /> </td></tr>";
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }                        
            }
        }
        doc += "</table></body></html>";
        chatListTextArea.setText(doc);
    }

    private void displayUserList() throws RemoteException {
        userListTextArea.setText("");
        users = chat.getAllUsers();
        for (String u : users) {
            if (!u.equals(username)) {             
                userListTextArea.append(" " + u + "\n");             
            }
        }
    }

    public void refresh() {
        try {
            displayChatList();
            displayUserList();
        } catch (RemoteException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setImages() {
        ImageIcon icons[] = new ImageIcon[10];
        for (int i = 0; i < 10; i++) {
            icons[i] = new ImageIcon(getClass().getResource("/images/" + i + ".png"));
        }
        hpyLabel.setIcon(icons[0]);
        lghLabel.setIcon(icons[1]);
        sadLabel.setIcon(icons[2]);
        supLabel.setIcon(icons[3]);
        tngLabel.setIcon(icons[4]);
        angLabel.setIcon(icons[5]);
        glsLabel.setIcon(icons[6]);
        ywnLabel.setIcon(icons[7]);
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        Message message = new Message();
        message.setUsername(username);
        message.setType("client");
        message.setDate(new Date());
        if (e.getSource() == hpyLabel) {
            message.setSmiley("0.png");
        } else if (e.getSource() == lghLabel) {
            message.setSmiley("1.png");
        } else if (e.getSource() == sadLabel) {
            message.setSmiley("2.png");
        } else if (e.getSource() == supLabel) {
            message.setSmiley("3.png");
        } else if (e.getSource() == tngLabel) {
            message.setSmiley("4.png");
        } else if (e.getSource() == angLabel) {
            message.setSmiley("5.png");
        } else if (e.getSource() == glsLabel) {
            message.setSmiley("6.png");
        } else if (e.getSource() == ywnLabel) {
            message.setSmiley("7.png");
        }
        try {
            chat.sendMessage(message);
        } catch (RemoteException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    private void addListeners() {
         hpyLabel.addMouseListener(this);
         lghLabel.addMouseListener(this);
         sadLabel.addMouseListener(this);
         supLabel.addMouseListener(this);
         tngLabel.addMouseListener(this);
         angLabel.addMouseListener(this);
         glsLabel.addMouseListener(this);
         ywnLabel.addMouseListener(this);
         chatInputText.addKeyListener(this);
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            sendNewMessage();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    private void sendNewMessage() {
        String inputMessage = chatInputText.getText();
        chatInputText.setText("");
        Message message = new Message();
        message.setUsername(username);
        message.setMsg(inputMessage);
        message.setType("client");
        message.setDate(new Date());
        try {
            chat.sendMessage(message);
        } catch (RemoteException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
